### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by max397574** [nellowly/dots#2]
is this config faster than a normal one?

**Comment by malisoft** [comment]
i loved using with dockers, but when i tried to compile locally in mac i can't 
![image](https://user-images.githubusercontent.com/55772887/215751158-60b761b4-7bbe-459e-b19f-31d039f70327.png)

**Comment by rewhile** [comment]
@malisoft https://spin.atomicobject.com/2022/01/28/gnu-compiler-collection/

Judging from this post I think you should use `gcc-11` instead of `gcc` on macos, not sure how to fix the Makefile so it works cross-platform though...
