### ISSUE TITLE
Lazy.nvim can not load plugins.

### ISSUE THREAD

**Issue by ghost** [nellowly/dots#3]
Hi @nullchilly, i downloaded your nvim settings to learn how to use it but when i opened the lazy.nvim can't load those plugins below:

Comment.nvim
cmp-buffer
cmp-nvim-lsp
cmp-path
fsread.nvim
gitsigns.nvim
hlargs.nvim
nvimautopairs
nvim-cmp
nvim-tree.lua
suda.vim
telescope.nvim
toggleterm.nvim
vim-airline
vim-airline-themes

I can use :Telescope and it pop up but i can't use gitsigns.nvim (it show nothing when i try :g in console). How can i fix it or i create a new file to require those plugins.

**Comment by ghost** [comment]
I really confuse that those settings will be loaded when i use plugins or it can't load because of error.

**Comment by rewhile** [comment]
You might be looking for https://github.com/folke/lazy.nvim#lazy-loading

I config those plugins to only load on some specific events or keymaps

**Comment by ghost** [comment]
Thanks @nullchilly <3, about gitsigns, how you use it. I need to cd into git repostory in my powershell to activate it???

**Comment by rewhile** [comment]
Yeah I only use gitsigns in a git repository anyway.. Not sure about other usages

**Comment by ghost** [comment]
Thanks
