### ISSUE TITLE
Neovim nightly initialization failure

### ISSUE THREAD

**Issue by doctorfree** [nellowly/dots#5]
I am incorporating `CatNvim` in the [Lazyman Neovim Configuration Manager](https://github.com/doctorfree/nvim-lazyman). It's very cool that you have written this config in `C`.

The config initializes correctly when using Neovim 0.9.1 but encounters an error when using Neovim nightly. I don't know why.

It appears that `lazy.nvim` is not getting downloaded, or is getting downloaded to the wrong location when using the nightly build.

That is, the `lazy.nvim` path may not be getting set correctly with:

```c
char *lazypath = concat_str(get_xdg_home(1), "lazy/lazy.nvim");
```

I don't really have any good ideas about why this would occur with the nightly build but not the stable build.
Can you verify this is the case?

Aside from that, I love this config and will be happy to include it in `Lazyman`.

**Comment by rewhile** [comment]
You're right, nightly requires the path ending with /

```diff
- char *lazypath = concat_str(get_xdg_home(1), "lazy/lazy.nvim");
+ char *lazypath = concat_str(get_xdg_home(1), "lazy/lazy.nvim/");
```

Seems to fix it, thanks!
